# Generated by Django 3.2 on 2021-10-10 18:46

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='feature',
            field=models.JSONField(default=payments.models.get_default_json_value_features),
        ),
    ]
